### ISSUE TITLE
new build results in ogp.js, but we don't use that in production

### ISSUE THREAD

**Issue by krdyke** [borchert/OGP2#5]
I'm confused...

I pulled to production the new code for feature service preview, but when I `mvn compile` it only writes to the `ogp.js` and `ogpLib.js` files, rather than the individual ones as has been the case previously.

**Comment by cheetah90** [comment]
Hi Kevin,

Not sure if I understand what you mean. Do you mean the ogp.js and ogpLib.js are generated but not used? That's because I modified the web/WEB-INF/views/jspf/include.jspf file to include the individual js files rather than the ogp.js file.

Does that answer the question? Let me know if you want me to change it back to using the ogp.js file.

**Comment by krdyke** [comment]
forgot to `mvn clean` before `mvn package`. good now
